<a href="https://colab.research.google.com/github/tharushi4/Mini_Project_EEX6278/blob/tharushi4-python-code/MiniProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [124]:
#import packages and import python libraries
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [125]:
from tensorflow.keras import layers,models,datasets
from tensorflow.keras.utils import to_categorical

In [126]:
data = pd.read_csv('/content/kidney_disease.csv')

In [127]:
data.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [128]:
#data cleaning and save cleaned dataset
data_cleaned = data.dropna()
data_cleaned.to_csv('cleaned_kidney_disease.csv', index=False)

In [129]:
# categirizing qualitative variables
categorical_cols = [
    'rbc','pc','pcc','ba','htn','dm','cad','appet','pe','ane','classification']

In [130]:
df = pd.read_csv("/content/cleaned_kidney_disease.csv")

In [131]:
df.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
1,9,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,...,29,12100,3.7,yes,yes,no,poor,no,yes,ckd
2,11,63.0,70.0,1.010,3.0,0.0,abnormal,abnormal,present,notpresent,...,32,4500,3.8,yes,yes,no,poor,yes,no,ckd
3,14,68.0,80.0,1.010,3.0,2.0,normal,abnormal,present,present,...,16,11000,2.6,yes,yes,yes,poor,yes,no,ckd
4,20,61.0,80.0,1.015,2.0,0.0,abnormal,abnormal,notpresent,notpresent,...,24,9200,3.2,yes,yes,yes,poor,yes,yes,ckd

In [132]:
#convert values into numbers
df['rbc'] = df['rbc'].map({'normal': 0, 'abnormal': 1})
df['pc'] = df['pc'].map({'normal': 0, 'abnormal': 1})
df['pcc'] = df['pcc'].map({'notpresent': 0, 'present': 1})
df['ba'] = df['ba'].map({'notpresent': 0, 'present': 1})

df['htn'] = df['htn'].map({'no': 0, 'yes': 1})
df['dm'] = df['dm'].map({'no': 0, 'yes': 1})
df['cad'] = df['cad'].map({'no': 0, 'yes': 1})

df['appet'] = df['appet'].map({'good': 0, 'poor': 1})
df['pe'] = df['pe'].map({'no': 0, 'yes': 1})
df['ane'] = df['ane'].map({'no': 0, 'yes': 1})

# Target column
df['classification'] = df['classification'].map({'notckd': 0, 'ckd': 1})

In [133]:
print(X_train.shape)
print(y_train.shape)

(126, 25)
(126,)

In [134]:
#handle missing values
df.fillna(df.mean(), inplace=True)

In [135]:
# split dataset
from sklearn.model_selection import train_test_split

X = df.drop('classification', axis=1)
y = df['classification']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [136]:
#train model
model = Sequential([
    Dense(32, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [137]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [138]:
input_shape=(X_train.shape[1],)

In [139]:
model.fit (X_train,y_train,batch_size=10,epochs=100,validation_split=0.2)

Epoch 1/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.2822 - loss: 355.7534 - val_accuracy: 0.4231 - val_loss: 7.4362
Epoch 2/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6543 - loss: 36.0171 - val_accuracy: 0.8077 - val_loss: 47.6231
Epoch 3/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6944 - loss: 60.5003 - val_accuracy: 0.3846 - val_loss: 9.3781
Epoch 4/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.3820 - loss: 17.6364 - val_accuracy: 0.8077 - val_loss: 9.0879
Epoch 5/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7480 - loss: 8.2272 - val_accuracy: 0.6923 - val_loss: 3.9911
Epoch 6/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6584 - loss: 4.8218 - val_accuracy: 0.9231 - val_loss: 0.7537
Epoch 7/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8728 - loss: 1.1786 - val_accuracy: 0.8846 - val_loss: 2.7298
Epoch 8/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9566 - loss: 0.4448 - val_accuracy: 0.8077 - val_loss: 1.3421
Epoch 9/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8291 - loss: 1.4506 - val_accuracy: 0.8846 - val_loss: 1.5362
Epoch 10/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9099 - loss: 0.3634 - val_accuracy: 0.8846 - val_loss: 1.2648
Epoch 11/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9466 - loss: 0.4068 - val_accuracy: 0.9231 - val_loss: 0.3802
Epoch 12/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9138 - loss: 0.3150 - val_accuracy: 0.8846 - val_loss: 2.4398
Epoch 13/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8619 - loss: 0.4259 - val_accuracy: 0.8077 - val_loss: 3.0625
Epoch 14/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8539 - loss: 1.1802 - val_accuracy: 0.8846 - val_loss: 0.2227
Epoch 15/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9551 - loss: 0.0975 - val_accuracy: 0.8846 - val_loss: 1.2564
Epoch 16/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9954 - loss: 0.0278 - val_accuracy: 0.9615 - val_loss: 0.3272
Epoch 17/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9835 - loss: 0.0977 - val_accuracy: 0.9231 - val_loss: 0.4919
Epoch 18/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9836 - loss: 0.0415 - val_accuracy: 0.8846 - val_loss: 0.9590
Epoch 19/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9457 - loss: 0.1610 - val_accuracy: 0.9615 - val_loss: 0.2882
Epoch 20/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9764 - loss: 0.0484 - val_accuracy: 0.9615 - val_loss: 0.2860
Epoch 21/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9960 - loss: 0.0097 - val_accuracy: 0.9615 - val_loss: 0.4033
Epoch 22/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9947 - loss: 0.0058 - val_accuracy: 0.8846 - val_loss: 0.5324
Epoch 23/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0177 - val_accuracy: 0.9615 - val_loss: 0.4012
Epoch 24/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.9615 - val_loss: 0.2553
Epoch 25/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9972 - loss: 0.0035 - val_accuracy: 0.9231 - val_loss: 0.4413
Epoch 26/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9947 - loss: 0.0261 - val_accuracy: 0.9231 - val_loss: 0.4668
Epoch 27/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9972 - loss: 0.0100 - val_accuracy: 0.9615 - val_loss: 0.3922
Epoch 28/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9891 - loss: 0.0444 - val_accuracy: 0.9231 - val_loss: 0.4641
Epoch 29/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9932 - loss: 0.0107 - val_accuracy: 0.8846 - val_loss: 0.7687
Epoch 30/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9846 - loss: 0.0571 - val_accuracy: 0.9615 - val_loss: 0.0801
Epoch 31/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9672 - loss: 0.0509 - val_accuracy: 0.8846 - val_loss: 0.5447
Epoch 32/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0058 - val_accuracy: 0.9615 - val_loss: 0.1997
Epoch 33/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9874 - loss: 0.0264 - val_accuracy: 0.8846 - val_loss: 0.9996
Epoch 34/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9932 - loss: 0.0179 - val_accuracy: 0.9615 - val_loss: 0.2468
Epoch 35/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9846 - loss: 0.0221 - val_accuracy: 0.8846 - val_loss: 2.2228
Epoch 36/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9365 - loss: 0.3061 - val_accuracy: 1.0000 - val_loss: 0.0497
Epoch 37/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9173 - loss: 0.4491 - val_accuracy: 0.8462 - val_loss: 0.5076
Epoch 38/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9139 - loss: 0.2366 - val_accuracy: 0.9615 - val_loss: 0.1313
Epoch 39/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9546 - loss: 0.0775 - val_accuracy: 0.8846 - val_loss: 0.7137
Epoch 40/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 0.9615 - val_loss: 0.3847
Epoch 41/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 2.6615e-04 - val_accuracy: 0.9615 - val_loss: 0.2501
Epoch 42/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 3.9122e-04 - val_accuracy: 0.9615 - val_loss: 0.2446
Epoch 43/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 6.8523e-05 - val_accuracy: 0.9615 - val_loss: 0.2761
Epoch 44/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 2.4449e-04 - val_accuracy: 0.9615 - val_loss: 0.2959
Epoch 45/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.8328e-04 - val_accuracy: 0.9615 - val_loss: 0.3012
Epoch 46/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 3.6601e-04 - val_accuracy: 0.9615 - val_loss: 0.2944
Epoch 47/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.4301e-04 - val_accuracy: 0.9615 - val_loss: 0.2967
Epoch 48/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 9.1857e-05 - val_accuracy: 0.9615 - val_loss: 0.2871
Epoch 49/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.3563e-04 - val_accuracy: 0.9615 - val_loss: 0.2804
Epoch 50/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 8.5166e-05 - val_accuracy: 0.9615 - val_loss: 0.2835
Epoch 51/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.3711e-04 - val_accuracy: 0.9615 - val_loss: 0.2871
Epoch 52/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.8867e-04 - val_accuracy: 0.9615 - val_loss: 0.2913
Epoch 53/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.3825e-04 - val_accuracy: 0.9615 - val_loss: 0.2914
Epoch 54/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 1.2482e-04 - val_accuracy: 0.9615 - val_loss: 0.2873
Epoch 55/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 1.7700e-04 - val_accuracy: 0.9615 - val_loss: 0.2850
Epoch 56/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.4878e-04 - val_accuracy: 0.9615 - val_loss: 0.2853
Epoch 57/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 2.7126e-04 - val_accuracy: 0.9615 - val_loss: 0.2909
Epoch 58/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 6.1591e-05 - val_accuracy: 0.9615 - val_loss: 0.2876
Epoch 59/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.8159e-04 - val_accuracy: 0.9615 - val_loss: 0.2849
Epoch 60/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.3571e-04 - val_accuracy: 0.9615 - val_loss: 0.2891
Epoch 61/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 2.1514e-04 - val_accuracy: 0.9615 - val_loss: 0.2859
Epoch 62/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 1.7697e-04 - val_accuracy: 0.9615 - val_loss: 0.2795
Epoch 63/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 4.0926e-04 - val_accuracy: 0.9615 - val_loss: 0.2900
Epoch 64/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 8.2974e-05 - val_accuracy: 0.9615 - val_loss: 0.2970
Epoch 65/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 2.0284e-04 - val_accuracy: 0.9615 - val_loss: 0.2873
Epoch 66/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.3492e-04 - val_accuracy: 0.9615 - val_loss: 0.2812
Epoch 67/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 1.1908e-04 - val_accuracy: 0.9615 - val_loss: 0.2846
Epoch 68/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.8885e-04 - val_accuracy: 0.9615 - val_loss: 0.2829
Epoch 69/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 2.9578e-04 - val_accuracy: 0.9615 - val_loss: 0.2900
Epoch 70/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.3496e-04 - val_accuracy: 0.9615 - val_loss: 0.2919
Epoch 71/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 9.5626e-05 - val_accuracy: 0.9615 - val_loss: 0.2910
Epoch 72/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.1416e-04 - val_accuracy: 0.9615 - val_loss: 0.2856
Epoch 73/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 1.2743e-04 - val_accuracy: 0.9615 - val_loss: 0.2801
Epoch 74/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 4.0771e-05 - val_accuracy: 0.9615 - val_loss: 0.2841
Epoch 75/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 2.2384e-04 - val_accuracy: 0.9615 - val_loss: 0.2879
Epoch 76/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 2.7711e-04 - val_accuracy: 0.9615 - val_loss: 0.2826
Epoch 77/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 5.3947e-05 - val_accuracy: 0.9615 - val_loss: 0.2865
Epoch 78/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 2.0330e-04 - val_accuracy: 0.9615 - val_loss: 0.2963
Epoch 79/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.1359e-04 - val_accuracy: 0.9615 - val_loss: 0.2898
Epoch 80/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 1.3485e-04 - val_accuracy: 0.9615 - val_loss: 0.2892
Epoch 81/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 2.2916e-04 - val_accuracy: 0.9615 - val_loss: 0.2793
Epoch 82/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 2.5281e-04 - val_accuracy: 0.9615 - val_loss: 0.2805
Epoch 83/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 2.9378e-04 - val_accuracy: 0.9615 - val_loss: 0.2854
Epoch 84/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 1.4673e-04 - val_accuracy: 0.9615 - val_loss: 0.2879
Epoch 85/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 2.6635e-04 - val_accuracy: 0.9615 - val_loss: 0.2817
Epoch 86/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 2.4886e-04 - val_accuracy: 0.9615 - val_loss: 0.2843
Epoch 87/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.4229e-04 - val_accuracy: 0.9615 - val_loss: 0.2936
Epoch 88/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 1.0000 - loss: 2.4944e-04 - val_accuracy: 0.9615 - val_loss: 0.2840
Epoch 89/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 6.6023e-05 - val_accuracy: 0.9615 - val_loss: 0.2831
Epoch 90/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 1.1820e-04 - val_accuracy: 0.9615 - val_loss: 0.2875
Epoch 91/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 1.4498e-04 - val_accuracy: 0.9615 - val_loss: 0.2869
Epoch 92/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 8.4904e-05 - val_accuracy: 0.9615 - val_loss: 0.2846
Epoch 93/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 1.7073e-04 - val_accuracy: 0.9615 - val_loss: 0.2803
Epoch 94/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 1.8989e-04 - val_accuracy: 0.9615 - val_loss: 0.2830
Epoch 95/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 1.0821e-04 - val_accuracy: 0.9615 - val_loss: 0.2900
Epoch 96/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 5.6700e-05 - val_accuracy: 0.9615 - val_loss: 0.2885
Epoch 97/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 1.7354e-04 - val_accuracy: 0.9615 - val_loss: 0.2817
Epoch 98/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 5.9154e-05 - val_accuracy: 0.9615 - val_loss: 0.2811
Epoch 99/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 3.5530e-05 - val_accuracy: 0.9615 - val_loss: 0.2848
Epoch 100/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 1.2547e-04 - val_accuracy: 0.9615 - val_loss: 0.2912